### ISSUE TITLE
Support google subscription v2

### ISSUE THREAD

**Issue by HerbertIV** [imdhemy/google-play-billing#29]
Please implemented object SubscriptionPurchase for subscriptionv2, 
https://developers.google.com/android-publisher/api-ref/rest/v3/purchases.subscriptionsv2/get?hl=pl

**Comment by imdhemy** [comment]
Hello Bot, I haven't had a chance to take a look at it yet.

**Comment by imdhemy** [comment]
Hey bot, we still want to add this feature :)
