### ISSUE TITLE
Trying to get the linked purchase token from a Google Play subscription fails when it is null

### ISSUE THREAD

**Issue by OrthoCube** [imdhemy/google-play-billing#3]
**Describe the bug**

The signature of the `getLinkedPurchaseToken` function requires that it returns string, however, for some purchases, the linked purchase token is not set, so it might return null, and this causes PHP to throw an error

**To Reproduce**

This is an excerpt from a Google Play event handler:

```
        $notification = $event->getServerNotification();
        $subscription = $notification->getSubscription();
        $token = $subscription->getUniqueIdentifier();

        $googleSubscription = $subscription->getProviderRepresentation();
        $googleSubscription->getLinkedPurchaseToken(); // <- error
````

**Expected behavior**
The function should return the linked purchase token (string) if it exists, or maybe `null` if it is not set for the specific purchase token.

**Screenshots**

```
Return value of Imdhemy\GooglePlay\Subscriptions\SubscriptionPurchase::getLinkedPurchaseToken() must be of the type string, null returned {"exception":"[object] (TypeError(code: 0): Return value of Imdhemy\\GooglePlay\\Subscriptions\\SubscriptionPurchase::getLinkedPurchaseToken() must be of the type string, null returned at /var/www/xxx/xxx/vendor/imdhemy/google-play-billing/src/Subscriptions/SubscriptionPurchase.php:231)
```

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu 20.04)
 - PHP: 7.4.3
 - this package's version: 0.9.0

**Additional context**

Funny thing is, while the file where the error occurs (SubscriptionPurchase.php:231) does exist on my laptop, I can't seem to find it in this repository. I don't know why.

**Comment by imdhemy** [comment]
Hi @OrthoCube,
Thank you for this awesome bug report. I moved this issue from [Laravel IAP](https://github.com/imdhemy/laravel-in-app-purchases) to this repository. I just published [v0.3.5](https://github.com/imdhemy/google-play-billing/releases/tag/0.3.5) and this bug is fixed. Just `run composer` update and make sure you're using `imdhemy/google-play-billing`: `0.3.5`.

```
composer update
composer show imdhemy/google-play-billing
```

BTW the additional context is so funny, you have a good sense of humor.

Dhemy,
