### ISSUE TITLE
getLinkedPurchaseToken|linkedPurchaseToken always null

### ISSUE THREAD

**Issue by iammart** [imdhemy/google-play-billing#4]
**Description**

`getLinkedPurchaseToken` always returns null

**Steps To Reproduce**

This is identical setup to the the recently closed issue #3 

**Expected behavior**

When I re signup from a subscription that has been expired and cancelled, it should return the `linkedPurchaseToken` allowing the listener of the event to find the original subscription and owner/user.

https://developer.android.com/google/play/billing/subscriptions#upgrade-downgrade

When the users performs this action in their play store account, it fires a new `SubscriptionPurchased` event.

**Other**

Im unsure if this is a casualty of testing using the sandbox.

When I inspect the SubscriptionPurchase object the protected property `linkedPurchaseToken` is definitely null.

**Comment by imdhemy** [comment]
Hi @iammart,

Thank you for reporting this issue. The `linkedPurchaseToken` property is parsed from the response body returned from Google REST API. Returning a `null` value means that the key is missing from the response body.

You can debug this [static factory method](https://github.com/imdhemy/google-play-billing/blob/master/src/Subscriptions/SubscriptionPurchase.php#L156) and check the returned body, If there is any logical bug, kindly inform me.

Dhemy,

**Comment by iammart** [comment]
Hey @imdhemy 

This is great - I totally missed this. I will definitely give this a shot.

After I posted the issue I did think it was a google related...or something im missing in their docs.

Thanks
