### ISSUE TITLE
Add support for Product "consume"

### ISSUE THREAD

**Issue by teyeheimans** [imdhemy/google-play-billing#95]
### Description

Currently it is possible to retrieve a purchase, and acknowledge it. However, it is not possible to consume a purchase. 

Therefore I would suggest to add a `consume` method to the `Imdhemy\GooglePlay\Products\ProductClient` class. 

See https://developers.google.com/android-publisher/api-ref/rest/v3/purchases.products/consume

**Comment by teyeheimans** [comment]
Kick

**Comment by imdhemy** [comment]
Hi @teyeheimans 
Consume is already implemented. 

https://github.com/imdhemy/google-play-billing/blob/bb94f3b6ddb021605815e528f31b8c930c41677c/src/Products/ProductClient.php#L82

**Comment by teyeheimans** [comment]
Ah perfect!
